# Generated by Django 5.1.2 on 2024-12-17 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JoinRequest",
        ),
    ]
