# Generated by Django 5.1.2 on 2024-12-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_joinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="joinrequest",
            name="joinded",
            field=models.BooleanField(default=False),
        ),
    ]
