# Generated by Django 5.1.2 on 2024-12-19 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_coursepayment_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studenttask",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.course"
            ),
        ),
        migrations.AlterField(
            model_name="studenttask",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_tasks",
                to="main.student",
            ),
        ),
    ]
