# Generated by Django 5.1.2 on 2024-12-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_studenttask_course_alter_studenttask_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
