# Generated by Django 5.1.2 on 2024-12-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="page_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
