# Generated by Django 5.1.2 on 2024-12-26 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_feedback_is_send"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joinrequest",
            name="student",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.student",
            ),
            preserve_default=False,
        ),
    ]
