# Generated by Django 5.1.2 on 2025-02-03 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_joinrequest_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='is_attended',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
