"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

import rest_framework.permissions

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from decouple import config

SECRET_KEY = config('SECRET_KEY')
DEBUG = True
# DATABASES = {
#     'default': dj_database_url.parse(config('DATABASE_URL'))
# }

# DATABASES = {
#     'default': {
#         # 'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': config('DBNAME'), 
#         'USER': config('DBUSER'),
#         'PASSWORD': config('DBPASS'),
#         'HOST': config('DBHOST'),
#         'PORT': config('DBPORT'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db.sqlite3',  # Replace with your desired database file name
    }
}

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # local
    'main',
    'api',
    # global
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'djoser',
    'corsheaders',
    'drf_yasg',
    'phonenumber_field', # telefon raqamlar uchun maydon yani field
    'crispy_forms',
    "crispy_bootstrap5",

]
# DRF permission
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASS': [
        # 'rest_framework.permissions.IsAdminUser',
        "rest_framework.permissions.AllowAny",
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

}

from datetime import timedelta
SIMPLE_JWT = {
    # 'AUTH_HEADER_TYPES': ('JWT',), # bu qo'shilgandan so'ng
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=120),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "TOKEN_OBTAIN_SERIALIZER": "api.serializers.MyTokenObtainPairSerializer",

}

#
# CORS_ALLOWED_ORIGINS = [ "*"]
#     # 'http://127.0.0.1:8000',
#     # 'http://127.0.0.1:3000',

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8081",   # React Native dev server
    "http://192.168.1.100",    # Django server
]




CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5500",
    "http://127.0.0.1:8000",
]



ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR / "template")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.base_translations",
            ],
        },
    },
]

AUTH_USER_MODEL = 'main.CustomUser'


WSGI_APPLICATION = "config.wsgi.application"
# settings.py
# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',  # Default Django backend (optional)
#     # 'main.authentication_backends.EmailAuthBackend',  # Path to your custom backend
# ]
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#
# DATABASES = {
#     'default': dj_database_url.parse(env('DATABASE_URL'))
# }






# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGES = [
    ('en', 'English'),
    ('uz', 'O\'zbekcha'),

]

LOCALE_PATHS = [
    BASE_DIR / 'locale',  # Tarjimalar uchun papka
]





# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en"

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_TZ = True

#ishla yaxshimi
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
import os

# STATIC_URL = config("STATIC_URL")
# STATIC_ROOT = os.path.join(BASE_DIR, config("STATIC_ROOT"))
# STATICFILES_DIRS = [BASE_DIR / config("STATIC_URL")]
# STATICFILES_FINDERS = [
#     'django.contrib.staticfiles.finders.FileSystemFinder',
#     'django.contrib.staticfiles.finders.AppDirectoriesFinder',
# ]

# # Media fayllar
# MEDIA_URL = config("MEDIA_URL")
# MEDIA_ROOT = os.path.join(BASE_DIR, config("MEDIA_ROOT"))

# Statik fayllar Windows uchun

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# settings.py

LOGIN_URL = '/login/'  # Kirish sahifangiz URL-manzilini ko‘rsating

LOGIN_REDIRECT_URL = 'index'  # Login qilgandan keyin qayta yo'naltirish uchun URL
LOGOUT_REDIRECT_URL = 'index'  # Logout qilgandan keyin qayta yo'naltirish uchun URL